# Generated by Django 5.0 on 2024-07-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(blank=True, max_length=50, null=True)),
                ('contactLastName', models.CharField(blank=True, max_length=50, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactMessage', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
