# Generated by Django 5.0 on 2024-07-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
