# Generated by Django 5.0 on 2024-07-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_hotelbooking_hotel_remove_hotelbooking_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
