# Generated by Django 5.0 on 2024-07-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_flightbooking_delete_flight_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightBooking',
        ),
    ]
